### ISSUE TITLE
Remember file tree state

### ISSUE THREAD

**Issue by mpeterson2** [mpeterson2/save-session#10]
It would be nice if the file tree was restored to its previous state. For example, if I expand a folder, select a file, and exit Atom, that folder should be expanded and that file should be selected again when I return to Atom.

This should be done separately per project since the file tree is very project specific. Because of this, it would probably be best to store this along with the project specific file buffers. So this issue should probably wait until file buffers are restored separately per project. 

- [x] ~~Fix issue #8~~
- [ ] Restore tree expansion
- [ ] Restore selected file

**Comment by rmenessec** [comment]
At present, save-session is not correctly remembering whether or not I had the tree open last time. (I don't use the tree.)

**Comment by mpeterson2** [comment]
This should be in Atom core now.
