### ISSUE TITLE
After restart, can't open tree view of open files

### ISSUE THREAD

**Issue by Strandbummler** [mpeterson2/save-session#107]
After I close and reopen Atom i cannot open the tree-view of open files. I have to close an reopen the files one by one to have it work again.

Atom Version 0.190.0 (0.190.0)
save-session 0.13.1
Mac OSX 10.10.3

**Comment by pronkman** [comment]
Not sure if this is related but I have same specs (except I'm using Atom Version 0.192.0) and I keep getting the same folder in tree view whether I restart Atom, open new window or close and reopen files in a different folder. It seems once a session is stored (directly after upgrading to version 0.13.1) it doesn't get updated.

**Comment by anthonyraymond** [comment]
Try to turn off the option "Restore file per project"

**Comment by mpeterson2** [comment]
Atom core should be handling this, so this should no longer be an issue for Save Session.
