### ISSUE TITLE
Uncaught Error: Invalid package /Users/yan/.atom/packages/save-session/projects//opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar

### ISSUE THREAD

**Issue by yangm97** [mpeterson2/save-session#110]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package, v0.14.0

### Stack Trace

Uncaught Error: Invalid package /Users/yan/.atom/packages/save-session/projects//opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar

```
At fs.js:55

Error: Invalid package /Users/yan/.atom/packages/save-session/projects//opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar
  at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:152:25)
  at Object.fs.writeFile (fs.js:1131:6)
  at /Users/yan/Dropbox/Mackup/.atom/packages/save-session/lib/files.coffee:41:9
  at /Users/yan/Dropbox/Mackup/.atom/packages/save-session/node_modules/mkdirp/index.js:29:20
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "core": {},
  "save-session": {
    "dataSaveFolder": "/Users/yan/.atom/packages/save-session/projects",
    "project": "/System/Library/Extensions/ProlificUsbSerial.kext",
    "windowX": 0,
    "windowY": 23,
    "windowWidth": 1280,
    "windowHeight": 709,
    "fullScreen": false,
    "projects": [
      "/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-update-packages, v0.2.2
autocomplete-plus, v2.12.1
editorconfig, v1.0.0
emmet, v2.3.8
highlight-line, v0.10.2
javascript-snippets, v1.0.0
jshint, v1.3.5
linter, v0.12.1
linter-csslint, v0.0.12
linter-jshint, v0.1.2
save-session, v0.14.0

# Dev
No dev packages
```

**Comment by mpeterson2** [comment]
This is because Save Session is incompatible with Atom versions greater than `0.193.0`. The Atom team has started integrating features of this package into the base application and there would be a lot of weird issues going on if you had this package installed.

If you want, you can change line 12 of [package.json](https://github.com/mpeterson2/save-session/blob/master/package.json#L12) to allow the package to be enabled.
