### ISSUE TITLE
Remove or refine deprecation notice

### ISSUE THREAD

**Issue by yissachar** [mpeterson2/save-session#111]
Not all features from this package are implemented in core. [Auto-saving untitled buffers](https://github.com/atom/atom/issues/942) is still an open issue for core Atom but is solved by this package.

The deprecation notice should either be removed entirely, or refined to clarify that not all functionality is supported by core Atom, and that this package is still useful.

**Comment by mpeterson2** [comment]
Done. I also just updated the package so it will be more compatible with Atom's latest releases.
