### ISSUE TITLE
Doesn't save session on direct closing

### ISSUE THREAD

**Issue by sanketmaru** [mpeterson2/save-session#114]
When Atom editor is closed using Quit command ( Ctrl + Q ) the session is restored. 

But when using close command (from the top right corner), it doesn't restore.

I am using latest atom editor 0.194.0.

**Comment by mpeterson2** [comment]
This is how Atom handles restoring. When you close out of a window, that project is no longer in your last session. But when you cmd+Q, any windows open are a part of your last session, and will be restored.

I just opened #115, which should solve the issue and keep Atom's way of restoring sessions.
