### ISSUE TITLE
Failure to restore on Atom upgrade

### ISSUE THREAD

**Issue by bmhkim** [mpeterson2/save-session#118]
When I have Atom restart and upgrade, my existing session(s) fail to restore. This reliably occurs for me.

Steps to reproduce:
1. Observe the blue squirrel in the bottom left corner, and click on it to go to release notes.
2. Click on the green button to restart and upgrade. (I forget its exact label)
3. Wait for Atom to restart, and observe that sessions failed to restore.

Atom: 0.208.0 (just upgraded from 0.207.0, but saw this on earlier upgrades)
save-session: 0.15.5
OS X 10.10.3

**Comment by mpeterson2** [comment]
Does it restore files or your project at least?

**Comment by bmhkim** [comment]
Everything is lost, open files and projects. I start with one empty window.

**Comment by mpeterson2** [comment]
Okay. That actually sounds like Atom's issue then. Save Session doesn't restore projects or open files anymore. All that it does now is restore unsaved files.

I'd open an issue with them.

**Comment by szabgab** [comment]
@mpeterson2 for me the problem only happened during the "restart and upgrade" which I personally initiated from the 'Atom' menu where it shows the current version number in row 3 and there was a 4th entry with "restart and upgrade".
Immediately after the restart I started with an empty session.

After the upgrade Save Session seems to work properly. Except maybe that now it keeps opening the Settings as an additional tab.

**Comment by mpeterson2** [comment]
Yeah, I understand the issue. Save Session doesn't deal with that stuff anymore. All it does now is restore file contents, while Atom core deals with restoring what files were open, your project, window size and whatever else.

**Comment by szabgab** [comment]
Oh I see. Thanks for the explanation!

**Comment by mpeterson2** [comment]
No problem.
