### ISSUE TITLE
Support panes

### ISSUE THREAD

**Issue by mpeterson2** [mpeterson2/save-session#12]
Save Session should have support for pane splitting. Right now, all files are reopened in the middle pane, but it would be nice if they could open in the pane it was originally in.

This would probably include editing the json a bit by adding the location of the pane to the file (not sure how to get that yet). When the file is opened, options can be specified to tell Atom to [open](https://atom.io/docs/api/v0.127.0/Workspace#instance-open) the file in a specified pane.

**Comment by mjrev** [comment]
+1

**Comment by tedyun** [comment]
+1

**Comment by svanharmelen** [comment]
+1

**Comment by greco** [comment]
+1

**Comment by mpeterson2** [comment]
This should be in Atom core now.
