### ISSUE TITLE
Save file dialog should show if closing via tab

### ISSUE THREAD

**Issue by Gabriel-p** [mpeterson2/save-session#123]
Currently the 'Save' dialog will not show if the option top not show it is selected and one either: exits atom or just closes the file by closing its tab.

`Sublime` handles this in a more "intelligent" way, *always* displaying the dialog if the file has unsaved changes and it is closed via its tab, but not showing it if the app itself is closed.

**Comment by mpeterson2** [comment]
Is this a duplicate of #121?

**Comment by Gabriel-p** [comment]
Yep. I'll go ahead and close this one.
