### ISSUE TITLE
The Settings window is always opened when starting Atom

### ISSUE THREAD

**Issue by Meligy** [mpeterson2/save-session#131]
When I use this package, every time I quit Atom and open it again, the "Settings" window ("Atom" -> "Preferences" on Mac) is opened again, even though it was not opened when I quit Atom.

I'm using Mac OS 10.10, and Atom 1.0.2.

P.S.
Thanks for the great effort BTW. This was the first plugin I looked for when considering moving from Sublime.

**Comment by mpeterson2** [comment]
That's strange. This package shouldn't touch the settings panel. Even if you had it open in the last session, it shouldn't try to reopen it. Try disabling the plugin and see if it still happens.

**Comment by Meligy** [comment]
I started noticing this just after installing `save-session` hence assumed it's related. Disabling the plugin doesn't help though, so it's NOT the plugin.

Sorry for that. I should have ran this simple test before creating the issue.

It's probably this one instead https://github.com/atom/atom/issues/7576 - Not sure.

**Comment by mpeterson2** [comment]
No worries. Thanks for confirming.
