### ISSUE TITLE
Session not saved

### ISSUE THREAD

**Issue by Burdu** [mpeterson2/save-session#140]
Just installed. Opened 2 tabs, closed atom, reopened it. No tabs restored.

This happened on Ubuntu 14.04 x64 with project path set to my home folder.
I believe that the plugin does not read the json on restore, because the tabs are correctly filled there on exit. (In /home/alex/.atom/packages/save-session/projects/home/alex/project.json)

I noticed that if I open other project folder, it restores it correctly.

**Comment by borekb** [comment]
Same here. It's nice that Atom doesn't prompt me for save when exiting the editor, it's less nice that the work is lost :)

**Comment by antonrufino** [comment]
I just installed Atom 1.1.0 and started having the same problem. It was working fine in Atom 1.0.

**Comment by dorkrawk** [comment]
I am also having the same issue in Atom 1.1.0 OSX 10.11.1

I can see things being written to the `project.json` but no files are restored.

**Comment by azda** [comment]
I just installed Atom 1.1.0 Windows 8 - file are not saved after closing Atom. I lost list of open files, and new unsaved file with some content

**Comment by wsssixteen** [comment]
It used to restore my tabs. Not sure if it has anything to do with updating Atom to 1.1.0. 
Am using windows 10, and save-session version 0.15.7.

**Comment by cbowns** [comment]
This has also regressed for me in the latest Atom version.

**Comment by ctwise** [comment]
atom 1.2, current save-session, type in first tab, open new tab, type in second tab, quit, re-open. First tab is restored, but no second tab.

**Comment by willwoodlief** [comment]
I cannot get atom to remember any of my tabs, does not promt me for unsaved work, and does not restore any tabs when restarting. This will happen no matter how many tabs I have open and modified.

**Comment by cbowns** [comment]
Created https://github.com/mpeterson2/save-session/issues/146 to track some of these. I think there's more nuance to these issues than a generic "session not saved", so let's start to track each issue as a specific thing.

**Comment by cbowns** [comment]
@ctwise Your issue sounds like #149.
