### ISSUE TITLE
Re-deprecate save-session

### ISSUE THREAD

**Issue by 50Wliu** [mpeterson2/save-session#154]
With Atom 1.4.0, Atom will start to autosave untitled buffers (atom/atom#9968), which I believe is the only thing keeping this package un-deprecated.  Just a heads-up @mpeterson2 :).

**Comment by mpeterson2** [comment]
Thanks for the heads up. It's now deprecated again.

**Comment by jbjonesjr** [comment]
atom 1.4 is not out yet. might want to add a note in the readme that this is scheduled for deprecation, but is still currently needed.
