### ISSUE TITLE
can not save session

### ISSUE THREAD

**Issue by aicochow** [mpeterson2/save-session#155]
when I new a file ,and input text,then close atom.
when I reopen atom,the file is not exist

**Comment by pvorona** [comment]
same here, windows 7, 10
Have 'backup before save' enabled and autosave-file plugin which can interfere somehow.

**Comment by tim-pl-m** [comment]
"Project Status: Deprecated

All of Save Session's functionality is now included in Atom core."
https://atom.io/packages/save-session

deactivating the package solved it for me ;)

**Comment by mpeterson2** [comment]
Yes, you should delete this package if you are using v1.4 of Atom.
