### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by iGadget73** [mpeterson2/save-session#167]
[Enter steps to reproduce:]

1. restarted atom after update to 1.39
2. saved a file from the recovered session
3. This pops up: (Restarting & such won't change a thing)

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.6
**Thrown From**: [save-session](https://github.com/mpeterson2/save-session) package 0.16.0

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:157

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:157:9)
    at Object.fs.writeFile (fs.js:1290:14)
    at /packages/save-session/lib/files.coffee:35:9
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:35:29
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:35:29
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:35:29
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:35:29
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:35:29
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:35:29
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:35:29
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:35:29
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:35:29
    at /packages/autocomplete-jsp/node_modules/mkdirp/index.js:47:53
    at FSReqWrap.oncomplete (fs.js:182:21)
```

### Commands

```
     -0:06.9.0 core:backspace (input.hidden-input)
     -0:06.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-css-unit-converter 1.1.1 
atom-html-preview 0.2.6 
atom-ignore 0.2.0 
atom-minify 0.8.0 
atom-minify-stand-alone 0.2.0 
atom-react-autocomplete 0.1.10 
atom-ternjs 0.19.1 
atom-twig 4.2.0 
autoclose 0.0.2 
autoclose-html 0.23.0 
autocomplete-json 5.5.2 
autocomplete-jsp 1.2.1 
autoprefixer 4.1.0 
bezier-curve-editor 0.7.2 
block-comment-plus 0.5.1 
caniuse 1.0.0 
close-tags 0.6.0 
color-picker 2.3.0 
compare-files 0.8.1 
compass 0.9.1 
console-panel 0.3.1 
css-snippets 1.1.0 
csslint 1.2.0 
drag-drop-text 0.1.4 
ds-ignore 0.1.0 
emmet 2.4.3 
escape-utils 0.5.3 
file-icons 2.1.33 
git-control 0.9.0 
git-log 0.4.1 
git-time-machine 2.1.0 
hey-pane 1.1.2 
hyperclick 0.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
js-hyperclick 1.17.0 
language-svg 0.9.2 
language-vue 0.24.0 
linter 2.3.0 
linter-eslint 8.5.5 
linter-flow 5.6.1 
local-history 4.3.1 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-split-diff 0.3.7 
open-plus 0.10.2 
open-recent 5.0.0 
php-cs-fixer 4.1.1 
php-twig 4.0.0 
pigments 0.40.2 
pretty-json 2.1.2 
preview-plus 1.2.7 
quick-vue 0.1.0 
sass-autocompile 0.13.5 
save-session 0.16.0 
ScssBundle 0.5.0 
simple-drag-drop-text 0.4.0 
sorter 1.3.0 
split-diff 1.6.0 
standardjs-snippets 2.6.2 
styri-syntax 1.0.0 
svg-preview 0.14.0 
svn 0.0.14 
symbols-tree-view 0.14.0 
sync-settings 0.8.6 
tag 0.5.0 
text-manipulation 0.6.0 
toggler 0.3.1 
touchbar 0.14.2 
uglify 1.3.1 
unity-ui 2.1.11 
vue-hyperclick 0.2.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by atalargo** [comment]
I have the same Issue
👍

**Comment by iGadget73** [comment]
I just disabled it. Seems to be core now, maybe that causes the problem? (Overlapping functionalities!?)

**Comment by michaeldrotar** [comment]
@iGadget73 what's the core package's name? I don't see it in mine, having the same issue

Update: I'm still unsure of which core package it is, but I can confirm if I disable `save-session`, fully quit atom, and open it again.. then all my windows/tabs are restored. Reopening a closed project also restores whichever tabs it was closed with and the error stops happening now.

Thanks!

**Comment by shirgans** [comment]
Right. this seems to be the issue - it's a core function now, so no need for the package. disable it, quit and relaunch Atom solves that issue. Thanks!

**Comment by iGadget73** [comment]
> what's the core package's name?

lol, of course I'm talking _in this repo about this repo_, aka **save-session**

**Comment by michaeldrotar** [comment]
> lol, of course I'm talking _in this repo about this repo_, aka **save-session**

Right, this is a _community package_, I was asking if you knew the _core package_ that replaces it.

It's okay though, homepage clarifies that this package is deprecated and links to the PR... for anyone else that finds their way here, can check the homepage for latest info:
https://github.com/mpeterson2/save-session

**Comment by iGadget73** [comment]
So: **remove _save-session_ from your atom, its core now**.

Case closed.
