### ISSUE TITLE
Remember/Restore multiple projects

### ISSUE THREAD

**Issue by uberbrady** [mpeterson2/save-session#17]
I had two 'projects' open at the same time - windows each with an array of tabs. When I quit and relaunched Atom, only the frontmost window was restored.

So I tend to have multiple projects open at the same time. So I am very excited to get this functionality back that I miss from Sublime Text!!! (I, in fact, continue to run Sublime just to have the Untitled File support. Perhaps no longer, now that I've found this!).

Here's how I was able to reproduce the issue - 

```sh
cd folder1
atom .
cd ../folder2
atom .
```

Then quit, and re-launch Atom. Only the folder2 'project' will be reopened.

**Comment by Santinell** [comment]
Now with version 0.182 of Atom feature of multiple projects became necessary (Multi root in one window)

**Comment by dmsimard** [comment]
Agreed, would love to have this work properly with the Atom feature of multiple root folders in the same window. It only re-opens one of the root folders.

**Comment by mpeterson2** [comment]
This should be in Atom core now.

**Comment by Goddard** [comment]
This feature is still not working in Atom latest build on Windows and Linux.  It only works in OSX.

**Comment by Santinell** [comment]
I thought so too, but after deleting all atom files and installing atom again - it works for me on Linux and Windows
