### ISSUE TITLE
Not restoring open files

### ISSUE THREAD

**Issue by burabure** [mpeterson2/save-session#25]
the tree and other simple data is restored fine, but the open files aren't.

im on ubuntu 14.04, atom v0.137.0

**Comment by hoffmannliu-ayla** [comment]
I just installed Atom together with Save Session package several minutes ago. And I had the same experience as that of @vmarkovtsev. No matter how I tried, I just couldn't make it work as expected. I am using Yosemite too.

Is there anything I can do to debug this ?

**Comment by hoffmannliu-ayla** [comment]
Today I updated Atom to 0.172.0 and save-session to 0.11.3 it works as expected now. I think maybe 0.11.3 fixed this.

**Comment by mpeterson2** [comment]
Glad to hear it's working for you. Is this still an issue for others or can we close this up?

**Comment by magic-lantern** [comment]
I'm running 0.174 and save session 0.11.3 and it is not saving my session. Any additional info needed that would help to troubleshoot this?

**Comment by mpeterson2** [comment]
Some things that can help are: are there any save-session related errors in the console? What other packages do you have installed? And what is your config?

**Comment by magic-lantern** [comment]
Here's my config:

"*":
  editor:
    invisibles: {}
  core:
    themes: [
      "atom-dark-ui"
      "base16-tomorrow-dark-theme"
    ]
  linter: {}
  "exception-reporting":
    userId: "363f270f-04cf-4653-abca-312511eb04bf"
  welcome:
    showOnStartup: false
  "save-session":
    dataSaveFolder: "/Users/seth/.atom/packages/save-session/projects"
    disableNewFileOnOpen: false
  autosave:
    enabled: true

Here's the packages I've installed:

language-r
linter
linter-csslint
linter-jscs
linter-jshint
linter-tidy
save-session
seti-monokai
seti-syntax
seti-ui
unity-dark-syntax
unity-dark-ui
unity-ui

When launching Atom, there are some warnings about save-session.

save-session (2 deprecations)
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on save-session repo
Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11
Object.addListeners - /Users/seth/.atom/packages/save-session/lib/project.coffee:34:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on save-session repo
Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11
Object.addListeners - /Users/seth/.atom/packages/save-session/lib/project.coffee:37:9


I tried uninstalling and re-installing a few times. It seems that now sometimes Atom remembers the session state and other times it doesn't. I'm on OSX, and always just quit out by doing Command Q, so I don't know why it sometimes remembers and other times not.

Perhaps it is just a PEBCAK error...

**Comment by mpeterson2** [comment]
It doesn't look like you have an issue with settings or conflicting packages.

Is this a recent problem or has it just started? The deprecation issue (#49) has just come up, so it could be that. I'll be looking into that issue soon.

**Comment by magic-lantern** [comment]
I have only attempted to use the "save-session" package recently. At this point, I can no longer replicate the problem. Perhaps through my multiple install/uninstall/remove Atom/re-install atom I removed some configuration or package that was conflicting.

Anyway, thanks for the help - save-session seems to be working great now.

**Comment by mpeterson2** [comment]
Well glad to hear it's working. I'm going to close this issue now.
