### ISSUE TITLE
Creating a new window from menubar duplicates an existing window

### ISSUE THREAD

**Issue by Dashed** [mpeterson2/save-session#41]
Creating a new window duplicates an existing window. I just want to create a new window with no state.

Useful for setting new tree view since the following isn't possible: https://github.com/atom/tree-view/issues/185

EDIT: see https://github.com/mpeterson2/save-session/issues/41#issuecomment-69109160

**Comment by mpeterson2** [comment]
How are you creating the new window? (keyboard shortcut, command pallete?)

**Comment by Dashed** [comment]
On interesting. Creating a new window via keyboard shortcut and command palette creates an empty window.

But from the menubar, `File > New Window`, duplicates the current window.

I'm using Atom `Version 0.167.0 (0.167.0)`

**Comment by mpeterson2** [comment]
Hmm your right. When the command `application:new-window` is triggered, the project path is cleared, so it is not reopened on the next window opening. However, the menubar version strangely doesn't seem to trigger `application:new-window`...

**Comment by mesosteros** [comment]
Yup, just tested this out. I was getting frustrated about opening a duplicate.
It would be great to have the new window option not duplicating the current project like the shortcut.
If I want to start a completely new blank project, I don't want to see the old one's file, file tree and contents.

**Comment by Dashed** [comment]
@mpeterson2 Could this be a regression in atom core?

**Comment by mpeterson2** [comment]
Yeah, I feel like Atom core should be triggering `application:new-window`. I don't think think it should work any differently from using the command palette or the shortcut.

**Comment by msssk** [comment]
It would be great if save-session could skip restoring the session in certain situations, such as "File -> New Window" from within Atom, or in the case of launching Atom from the command-line with parameters provided (like typing "atom ." to launch Atom with the current folder opened).

**Comment by mpeterson2** [comment]
This issue should be resolved now.
