### ISSUE TITLE
Uncaught Error: ENOENT, open 'undefined//Users/alopex/.atom/project.json'

### ISSUE THREAD

**Issue by benogle** [mpeterson2/save-session#43]
_From @SimyungYang on January 6, 2015 0:47_

[Enter steps to reproduce below:]

1. start an atom editor with save-session plugin on
2. save action might cause this error

**Atom Version**: 0.166.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open 'undefined//Users/alopex/.atom/project.json'

```
At fs.js:75

Error: ENOENT, open 'undefined//Users/alopex/.atom/project.json'
  at Error (native)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "npm-install",
      "save-session"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "editor": {
    "fontSize": 14,
    "invisibles": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
linter, v0.9.1
minimap, v3.5.0
save-session, v0.11.2
npm-install, v2.0.0

# Dev
No dev packages
```

_Copied from original issue: atom/atom#4854_

**Comment by clhynfield** [comment]
I think @vraravam is onto something with this in #45: 

> Also noticed that the preference setting for ''dataSaveFolder' (which was set to '/Users/vijay/.atom/packages/save-session/projects') keeps getting removed from the '.atom/config.cson' file and this could be the reason for the beginning value of 'undefined' when this plugin is trying to figure out the location of the 'project.json' file.

save-session [prepends `dataSaveFolder` to the path to project.json](https://github.com/mpeterson2/save-session/blob/master/lib/config.coffee#L80) (looked up through `@saveFolder`), but since it's now undefined, it's literally prepending "undefined", which results in an invalid path. I don't see in the package where this gets set, so I'm guessing maybe it's a core or global config that changed in 166.

**Comment by benogle** [comment]
@clhynfield what does your config contain for `save-session`? Config things did change in 166. 

cc @maxbrunsfeld

**Comment by clhynfield** [comment]
```cson
  'save-session':
    'project': '/Users/clayton/.atom'
    'windowX': 0
    'windowY': 23
    'windowWidth': 1280
    'windowHeight': 773
    'treeSize': 201
```

Also, as @vraravam notes in #45, even when I set `dataSaveFolder` manually in ~/.atom/config.cson, it's gone again shortly after.

**Comment by benogle** [comment]
There were some large config changes in 166. @maxbrunsfeld should know more.

**Comment by maxbrunsfeld** [comment]
Looking into it now.

**Comment by maxbrunsfeld** [comment]
My first guess is that it's because `dataSaveFolder` is not present in [`save-session`'s config schema](https://github.com/mpeterson2/save-session/blob/master/lib/save-session.coffee#L12). Schemas are now enforced in certain cases where they weren't before.

Looking into it deeper to verify.

**Comment by clhynfield** [comment]
Thanks very much, @maxbrunsfeld, that was it. I added this to the default config in save-session.coffee, and the package is working as expected: 

```cson
    dataSaveFolder:
      type: 'string'
      description: 'The folder in which to save project states'
```

I'll submit a PR shortly.

**Comment by maxbrunsfeld** [comment]
Great! Thanks @clhynfield.

**Comment by clhynfield** [comment]
Couple of asides out of this: 

1. Direct file IO seems like a kludgy way to save project/workspace state—is there a more Atom-y way to do this?

2. The error messages and stack traces caused by this third-party package didn't implicate the package in any way. I imagine this could cause serious headaches for the core Atom team as packages proliferate.

**Comment by maxbrunsfeld** [comment]
1. The package system already allows packages [to save and load state](https://atom.io/docs/v0.166.0/creating-a-package#source-code) as part of activation and deactivation. I'm not familiar with all of `save-session`'s functionality, so I don't know if loading its saved state at package activation time would work.

2. The notification system will associate errors with packages when possible, but often the stack trace doesn't contain enough information to do this. Perhaps we could use node's [domain system](http://nodejs.org/api/domain.html) to associate async stack traces with the packages that created them, but this might be more work than it's worth.

**Comment by clhynfield** [comment]
I figured serialization might be the way to do it. Dunno if @mpeterson2 has looked at that, but if I get the time, I'll see if it'll work. Thanks again, @maxbrunsfeld!

**Comment by mpeterson2** [comment]
I haven't had time to look into this yet. I see a few of you have forked this, so I'd be happy to accept a pull request if you guys can find a fix.

**Comment by clhynfield** [comment]
Working it up now, @mpeterson2. Thanks much.

**Comment by mpeterson2** [comment]
Just merged a few pull requests in that fixed the issue for me. Thanks for the help guys.

Reopen this if you still have issues.
