### ISSUE TITLE
Breaks in Atom 166

### ISSUE THREAD

**Issue by paradox460** [mpeterson2/save-session#46]
If you upgrade to Atom 166, you get a constant stream of errors from this plugin :(

People have opened several tickets for this so far:

+ #43
+ #45 

Additionally, it appears a PR is already opened fixing this, although I don't know if it actually does: #44

**Comment by paradox460** [comment]
Nevermind, it wasn't shadow dom causing it. It is still an issue, however.

**Comment by mpeterson2** [comment]
Should be fixed in 0.11.3
