### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by victorhooi** [mpeterson2/save-session#50]
When I start up Atom (0.174.0), I get the following deprecation warning:

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.addListeners (/Users/victorhooi/.atom/packages/save-session/lib/project.coffee:37:9)
```

**Comment by mpeterson2** [comment]
Going to close this as it is a duplicate of #49.
