### ISSUE TITLE
atom.workspaceView is deprecated.

### ISSUE THREAD

**Issue by hammackj** [mpeterson2/save-session#55]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:55:11)
Object.addListeners (/Users/hammackj/.atom/packages/save-session/lib/project.coffee:34:9)
```

**Comment by mpeterson2** [comment]
Whoops, edited the wrong issue title. Anyway this is a duplicate of #49, so I'm going to close this.
