### ISSUE TITLE
save-session restoring tabs in random order

### ISSUE THREAD

**Issue by rmenessec** [mpeterson2/save-session#59]
save-session on multiple machines (Linux, Windows) seems to restore tabs in random order. Is this a known issue?

This is a life-saving extension for Atom. I would not have switched away from Sublime without it. Thanks for the great work!

**Comment by mpeterson2** [comment]
Yeah, the reason for this is because the files open asynchronously. I'm not really sure if there is a good fix for this at the moment.

**Comment by rmenessec** [comment]
Dadgummit. Well, thanks for the fast response, then. ;)

**Comment by rmenessec** [comment]
Should have thought of this yday: is it possible to apply a work-around by rearranging the tabs after they load? I have no familiarity with what interfaces are exposed to Atom extensions.

**Comment by mpeterson2** [comment]
I've tried messing around with stuff after the files were all open, but it never seemed to work correctly. I'd wait for all the futures to end, but for some reason, they would all end before the files were actually there, and I'm not sure why.

I'm definitely not saying that it isn't possible, but I haven't been able to do it yet.

**Comment by mpeterson2** [comment]
This shouldn't be an issue anymore since Atom core is now dealing with this.
