### ISSUE TITLE
Disable New File On Open not working

### ISSUE THREAD

**Issue by iskatu** [mpeterson2/save-session#65]
When I open up Atom it always show the readme.md file instead of my last opened folder even though "Disable New File On Open" is checked in the package settings.

Warning in console:
```
'save-session.dataSaveFolder' could not set the default. Attempted default: undefined; Schema: {"type":"string","description":"The folder in which to save project states"}
```

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
