### ISSUE TITLE
Uncaught Error: ENOENT, open '/Users/projetmbc/.atom/packages/save-session/projects/undefined/project.json'

### ISSUE THREAD

**Issue by projetmbc** [mpeterson2/save-session#68]
Hello. I have safely reinstalled Atom after using a "dangerous" package named "sync-settings".

1. I have removed the folder `.atom` and the `atom` application. Maybe there are some other files to remove...
2. I have installed some starred packages using `apm`.

## The error message

    **Atom Version**: 0.178.0
    **System**: Mac OS X 10.8.5
    **Thrown From**: Atom Core

    ### Stack Trace

    Uncaught Error: ENOENT, open '/Users/projetmbc/.atom/packages/save-session/projects/undefined/project.json'

    ```
    At fs.js:82

    Error: ENOENT, open '/Users/projetmbc/.atom/packages/save-session/projects/undefined/project.json'
      at Error (native)

    ```

    ### Commands

    ```
         -0:01.6 application:new-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
    ```

    ### Config

    ```json
    {
      "core": {
        "themes": [
          "atom-dark-ui",
          "atom-dark-syntax"
        ]
      },
      "editor": {
        "fontSize": 16
      }
    }
    ```

    ### Installed Packages

    ```coffee
    # User
    autocomplete-paths, v1.0.2
    autocomplete-plus, v2.1.4
    color-picker, v1.4.4
    emmet, v2.3.3
    file-icons, v1.4.9
    hex, v0.5.0
    html-entities, v0.3.1
    minimap, v4.1.4
    parcel, v0.0.3
    save-session, v0.11.5
    show-in-folder, v0.1.0
    symbols-tree-view, v0.5.2
    tree-view-open-files, v0.2.3

    # Dev
    No dev packages
    ```

**Comment by zl4bv** [comment]
I get this error occasionally too.

1. Open an existing file
2. Make changes to the file
3. Ctrl+s
4. Sometimes the error is thrown, however it does not seem to affect the saving of the file

Since it does not occur every time I save I have not been able to pinpoint exactly what condition occurs to trigger the error and therefore cannot reliably replicate the issue.

**Atom Version**: 0.186.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: UNKNOWN, open 'C:\Users\ben.vidulich\.atom\packages\save-session\projects\undefined\project.json'

```
At fs.js:82

Error: UNKNOWN, open 'C:\Users\ben.vidulich\.atom\packages\save-session\projects\undefined\project.json'
  at Error (native)

```

### Commands

```
     -9:39.3 core:save (atom-text-editor.editor.is-focused)
     -7:42.8 application:new-file (atom-text-editor.editor.is-focused)
     -7:42.1 core:paste (atom-text-editor.editor)
  6x -0:47.0 core:delete (atom-text-editor.editor)
     -0:43.3 core:save (atom-text-editor.editor)
     -0:16.5 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:03.9 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.2 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-eighties-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autocomplete-ruby"
    ]
  },
  "editor": {
    "fontSize": 14,
    "invisibles": {},
    "softWrap": true,
    "scrollPastEnd": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.4.0
base16-eighties-dark-syntax, v0.1.0
file-icons, v1.5.0
linter, v0.12.0
linter-js-yaml, v1.0.0
linter-rubocop, v0.2.2
linter-ruby, v0.1.4
minimap, v4.5.0
minimap-git-diff, v4.1.2
save-session, v0.11.5

# Dev
No dev packages
```

**Comment by xdumaine** [comment]
This looks similar to the fix in #81. Can you update to the latest and see if this fixes the problem?

**Comment by zl4bv** [comment]
The problem appears to be fixed now - or at least it doesn't throw the error when I roughly replicate the steps I took before.

**Comment by mpeterson2** [comment]
Okay cool. If anyone else has the issue, let me know.
