### ISSUE TITLE
I'm getting the same issue as #18!

### ISSUE THREAD

**Issue by pookah-net** [mpeterson2/save-session#70]
When I open a new window, it's opening a slew of "untitled" tabs, plus a tab for every file I have open in Atom!

I'm running OS X Yosemite; I installed Atom just a couple of days ago (v 0.180.0). The Save-Session package is up to date.

/Ian

**Comment by mpeterson2** [comment]
Closing old issues that are probably irrelevant to the code just to clear up the clutter. Go ahead and open a new issue if there is still a problem.
