### ISSUE TITLE
Multiple projects since 0.182

### ISSUE THREAD

**Issue by anthonyraymond** [mpeterson2/save-session#73]
Since v0.182 we are now able to open multiple root folder in tree-view, unfortunately, only one is restored after closing and reopening Atom.

![image](https://cloud.githubusercontent.com/assets/7503585/6428579/9d2c2298-bfa8-11e4-9351-a99bc15a1ca3.png)

Images : 

1 : I just opened two root folders, and opened one file in each.
2 : Close and reopen Atom, save-session restore each files but does not restore the second root folder
![output_wad7al](https://cloud.githubusercontent.com/assets/7503585/6428645/52b8ec58-bfaa-11e4-9c17-1b269ec2111e.gif)

**Comment by saada** [comment]
:+1:

**Comment by xdumaine** [comment]
Yeah this is annoying as hell. Have one project open in a window. Go to another directory in terminal, run

**Comment by quarterto** [comment]
This should be as easy as replacing `atom.project.getPath` and `setPath` with `getPaths` and `setPaths`.

**Comment by jmatsushita** [comment]
+1 !

**Comment by xeor** [comment]
Absolutely, this is a must for this plugin.

Based on https://github.com/mpeterson2/save-session/blob/master/lib/config.coffee#L86-L87, it looks like the first project is always selected. https://github.com/mpeterson2/save-session/pull/81 looks somewhat related...

**Comment by anthonyraymond** [comment]
I started to look at the deprecated calls tonight (fixed , and finally found myself investigating at the mutiproject thing.
I have a working version here, and i also fixed the #86 issue. At the moment @mpeterson2 removed the "restore on start atom" which is in my opinion not the expected behavior, for i believe a lot of people.

Just need some time to write some tests (i someone can help me, cause i have no idea how specs works) so i'll can pull request soon.

I believe i fixed issues : #86, #73, #91, #92, #95, #97

**Comment by mpeterson2** [comment]
Should be fixed in `0.13.0`
