### ISSUE TITLE
Projects getting mixed up after upgrade to 0.184

### ISSUE THREAD

**Issue by smiffy6969** [mpeterson2/save-session#75]
I just upgraded to 184 yesterday... since then I have been getting issues with this package.

I open a single project, work on it, leave say 3 tabs open.

If I open another project, say i go file, open recent....  I now get a new window open.... it has the tabs in it from the other window though.

If I now close the tab I didn't want from the other project, open a file I do want, then close the window and also close the original window..... when I restart atom I get the original window open as I would exepect but the tabs are from both of the projects I opened.

At one point yesterday I started atom, then went to choose a another recent folder to open and it would only ever open one project, no matter what folder I choose.

It is giving me unpredictable results opening folders from scratch, or if opening from recent folders I seem to be getting a mash of lots of projects tabs opening...

On checking the projects folder in the save-session dir, I would expect to be seeing a folder for each project that was opened? I am not getting this, no matter how many folders I open (projects I start) I seem to only ever have one folder in the proects folder and that is called 'undefined' which happens to be JS for not set.... which makes me believe the package cannot grab the project/session/folder name or whatever it uses to connect a folder/project to a session, and it is dumping all project data into this one folder which is what is maching all my sessions together.

Had to disable this as it is proving to be a PITA.

ta

Paul

p.s. I have tried removing and re-installing

**Comment by xdumaine** [comment]
Yeah this is annoying as hell. Have one project directory open in a window. Go to another directory in terminal, run atom . to launch a new window in that directory, but end up with two from the first project directory.

**Comment by smiffy6969** [comment]
I agree, completely unusable now as of 0.184.... shame

**Comment by smiffy6969** [comment]
Just noticed a new version 0.12.0 come through but this extension is still severely broken and unusable..... if you cannot open more than 1 project ever then it is unusable. is this going to be fixed? or do i have to do it myself?

**Comment by smiffy6969** [comment]
.... ok i got really fed up with this bug.... fixed https://github.com/smiffy6969/save-session and added pull request.

**Comment by smiffy6969** [comment]
@xdumaine hiya, can you confirm if this fix solves your problem?

**Comment by mpeterson2** [comment]
Should be fixed with #81 which is included with version 0.12.1.

**Comment by smiffy6969** [comment]
Already updated from atom and is all working..... Thanks a lot, I have my editor back. 
Sent using CloudMagic
On Thu, Mar 19, 2015 at 7:52 pm, Michael Peterson <notifications@github.com> wrote:Should be fixed with #81 which is included with version 0.12.1.
