### ISSUE TITLE
Can't open new folder !!!

### ISSUE THREAD

**Issue by borkobt** [mpeterson2/save-session#76]
I can't open a new folder,because it always opens the new window with the already saved folder.
The scenario is folder opened in Atom, session is saved.
I trie to open a new folder, but i get the same folder in a new window.

**Comment by zagnut999** [comment]
I'm also experiencing this.  osx, current versions of atom/save-session.  I
hadn't narrowed it down to this plugin, though.  Hopefully it is and can be
fixed, because it's annoying.

**Comment by mpeterson2** [comment]
Is this a duplicate of #41? The problem is that Atom doesn't trigger the new window event when it's done through the menu bar, so as far as I know, it's not possible to tell that you are opening a new window.

**Comment by sinkingshriek** [comment]
@mpeterson2 It looks like it. Also, same behavior if you try to open another directory/folder.

**Comment by borkobt** [comment]
I use Project manager plugin, i works great, and has the features i need:
https://atom.io/packages/project-manager

**Comment by sinkingshriek** [comment]
@borkobt That package doesn't seem to remember any unsaved files which `save-session` primarily does.

**Comment by mpeterson2** [comment]
Okay. I'm going to close this as a duplicate of #41.
