### ISSUE TITLE
Cannot open folder

### ISSUE THREAD

**Issue by alayii** [mpeterson2/save-session#87]
When I open folder, new window will restore to old project, cannot open new one. how can I fix it?

**Comment by alayii** [comment]
ok, when I not check Restore Project and reopen atom.  it report issue https://github.com/mpeterson2/save-session/issues/84.

then I check Restore Project again, reopen atom, everything works fine. include open folder functionality.

**Comment by mpeterson2** [comment]
I believe 0.12.5 should help with this issue.

**Comment by alayii** [comment]
great, it works now :)
