### ISSUE TITLE
Opening a file with Atom does not focus the file

### ISSUE THREAD

**Issue by Chris54721** [mpeterson2/save-session#88]
![atom-save](https://cloud.githubusercontent.com/assets/3685659/6791043/578030e8-d1ac-11e4-9ada-da083c85790a.gif)
When opening a file with Atom, the new file tab isn't focused. It looks like the session tabs are opened after the file itself.

**Comment by mpeterson2** [comment]
Yeah, earlier on I looked into how to make a specific tab be focused and it didn't seem possible with their API. They may have implemented something for that now though.

**Comment by mpeterson2** [comment]
This shouldn't be an issue here anymore since Atom core is handling this now.
