### ISSUE TITLE
When opening a new project from atom cli, the save-session opens a different directory

### ISSUE THREAD

**Issue by xdumaine** [mpeterson2/save-session#89]
Seems to happen if you don't have a session saved for the session being opened from the command line. I.e., `mkdir save-session-test && cd save-session-test && atom .` will open a different directory in atom.

**Comment by mpeterson2** [comment]
This used to be solved by not restoring the project path when the path already existed. However, it seems that the package is now activated before a project is set.

**Comment by mpeterson2** [comment]
I believe 0.12.5 should help with this issue.

**Comment by xdumaine** [comment]
Still happening with 0.13.x

**Comment by mpeterson2** [comment]
Yes it is. I was trying it when Atom was already opened, so the issue wasn't there. Going to reopen this.

**Comment by mpeterson2** [comment]
Atom core should be handling this now, so this shouldn't be an issue here anymore.
